# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-28 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callback',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callback',
            name='target_url',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='hook',
            name='content_type',
            field=models.CharField(blank=True, choices=[('application/json', 'application/json'), ('application/xml', 'application/xml'), ('text/xml', 'text/xml'), ('text/plain', 'text/plain'), ('application/javascript', 'application/javascript'), ('text/html', 'text/html')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='hook',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hook',
            name='http_method',
            field=models.CharField(blank=True, choices=[('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('GET', 'GET'), ('DELETE', 'DELETE')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='hook',
            name='model',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='hook',
            name='payload_template',
            field=models.TextField(blank=True, help_text='Use {{}} for any variable template', null=True),
        ),
        migrations.AlterField(
            model_name='hook',
            name='target_url',
            field=models.URLField(max_length=512),
        ),
    ]
